m=float(input('Digite um valor em metros:'))
print('{} metros tem: '.format(m))
print('{} cm'.format(m*100))
print('{} mm'.format(m*1000))
print('{} km'.format(m/1000))
print('{} hm'.format(m/100))
print('{} dam'.format(m/10))