algo=input('Digite algo: ')
print('O tipo primitivo desse valor é ',type(algo))
print('Só tem espaço?', algo.isspace())
print('É alfabetico?',algo.isalpha())
print('É um número?',algo.isnumeric())
print('É alfanúmerico?', algo.isalnum())
print('É decimal?',algo.isdecimal())
print('É maisucula?',algo.isupper())
print('É minuscula?',algo.islower())
print('É capitalizada?',algo.istitle())